# Generated by Django 3.2.2 on 2021-06-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meTube', '0002_alter_appuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='avatar',
            field=models.ImageField(blank=True, height_field=500, upload_to='avatar/', verbose_name='Avatar', width_field=500),
        ),
    ]
