# Generated by Django 3.2.2 on 2021-07-11 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meTube', '0004_appuser_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='video',
            name='filename',
            field=models.FilePathField(default=None, path=None, unique=True, verbose_name='File'),
        ),
    ]
