# Generated by Django 3.2.2 on 2021-07-14 12:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meTube', '0005_auto_20210711_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='date_updated',
        ),
        migrations.AddField(
            model_name='appuser',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Modified'),
        ),
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Added'),
        ),
        migrations.AddField(
            model_name='like',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Added'),
        ),
        migrations.AddField(
            model_name='reply',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Added'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='video',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Added'),
        ),
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date Added')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meTube.appuser', verbose_name='User')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meTube.video', verbose_name='Video')),
            ],
            options={
                'verbose_name': 'View',
                'verbose_name_plural': 'Views',
            },
        ),
    ]
