# Generated by Django 3.2.2 on 2021-07-14 14:00

from django.db import migrations, models
import meTube.models


class Migration(migrations.Migration):

    dependencies = [
        ('meTube', '0006_auto_20210714_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='filename',
        ),
        migrations.AddField(
            model_name='video',
            name='video',
            field=models.FileField(default=None, upload_to=meTube.models.video_upload_path, verbose_name='File'),
            preserve_default=False,
        ),
    ]
