# Generated by Django 3.2.2 on 2021-07-14 14:01

from django.db import migrations, models
import meTube.models


class Migration(migrations.Migration):

    dependencies = [
        ('meTube', '0007_auto_20210714_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to=meTube.models.video_upload_path, verbose_name='Video'),
        ),
    ]
